### ISSUE TITLE
Provide attribution

### ISSUE THREAD

**Issue by ghost** [hariseenivasan/misc_py#1]
Hi, you took my script from the SpiceWorks site here: https://community.spiceworks.com/scripts/show/982-download-all-dilbert-comics

Please provide attribution in some form or take this down, thanks.

**Comment by hariseenivasan** [comment]
Yes, I did use reference. I am updating the readme.MD to contain your
original link. Also please let me know what other way I can provide. I am
going to put link as comment in python file too.

**Comment by ghost** [comment]
That'd be fine, thanks.

**Comment by hariseenivasan** [comment]
I have provided as stated.
